/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDocumentsRouteImport } from './routes/_authed/documents'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'
import { Route as AuthedDocumentsIndexRouteImport } from './routes/_authed/documents/index'
import { Route as AuthedChatIndexRouteImport } from './routes/_authed/chat/index'
import { Route as AuthedDocumentsUploadRouteImport } from './routes/_authed/documents/upload'
import { Route as AuthedDocumentsIdRouteImport } from './routes/_authed/documents/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDocumentsRoute = AuthedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentsIndexRoute = AuthedDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDocumentsRoute,
} as any)
const AuthedChatIndexRoute = AuthedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedChatRoute,
} as any)
const AuthedDocumentsUploadRoute = AuthedDocumentsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthedDocumentsRoute,
} as any)
const AuthedDocumentsIdRoute = AuthedDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedDocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/chat': typeof AuthedChatRouteWithChildren
  '/documents': typeof AuthedDocumentsRouteWithChildren
  '/documents/$id': typeof AuthedDocumentsIdRoute
  '/documents/upload': typeof AuthedDocumentsUploadRoute
  '/chat/': typeof AuthedChatIndexRoute
  '/documents/': typeof AuthedDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/documents/$id': typeof AuthedDocumentsIdRoute
  '/documents/upload': typeof AuthedDocumentsUploadRoute
  '/chat': typeof AuthedChatIndexRoute
  '/documents': typeof AuthedDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/chat': typeof AuthedChatRouteWithChildren
  '/_authed/documents': typeof AuthedDocumentsRouteWithChildren
  '/_authed/documents/$id': typeof AuthedDocumentsIdRoute
  '/_authed/documents/upload': typeof AuthedDocumentsUploadRoute
  '/_authed/chat/': typeof AuthedChatIndexRoute
  '/_authed/documents/': typeof AuthedDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/chat'
    | '/documents'
    | '/documents/$id'
    | '/documents/upload'
    | '/chat/'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/documents/$id'
    | '/documents/upload'
    | '/chat'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/chat'
    | '/_authed/documents'
    | '/_authed/documents/$id'
    | '/_authed/documents/upload'
    | '/_authed/chat/'
    | '/_authed/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/documents': {
      id: '/_authed/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthedDocumentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documents/': {
      id: '/_authed/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthedDocumentsIndexRouteImport
      parentRoute: typeof AuthedDocumentsRoute
    }
    '/_authed/chat/': {
      id: '/_authed/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthedChatIndexRouteImport
      parentRoute: typeof AuthedChatRoute
    }
    '/_authed/documents/upload': {
      id: '/_authed/documents/upload'
      path: '/upload'
      fullPath: '/documents/upload'
      preLoaderRoute: typeof AuthedDocumentsUploadRouteImport
      parentRoute: typeof AuthedDocumentsRoute
    }
    '/_authed/documents/$id': {
      id: '/_authed/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthedDocumentsIdRouteImport
      parentRoute: typeof AuthedDocumentsRoute
    }
  }
}

interface AuthedChatRouteChildren {
  AuthedChatIndexRoute: typeof AuthedChatIndexRoute
}

const AuthedChatRouteChildren: AuthedChatRouteChildren = {
  AuthedChatIndexRoute: AuthedChatIndexRoute,
}

const AuthedChatRouteWithChildren = AuthedChatRoute._addFileChildren(
  AuthedChatRouteChildren,
)

interface AuthedDocumentsRouteChildren {
  AuthedDocumentsIdRoute: typeof AuthedDocumentsIdRoute
  AuthedDocumentsUploadRoute: typeof AuthedDocumentsUploadRoute
  AuthedDocumentsIndexRoute: typeof AuthedDocumentsIndexRoute
}

const AuthedDocumentsRouteChildren: AuthedDocumentsRouteChildren = {
  AuthedDocumentsIdRoute: AuthedDocumentsIdRoute,
  AuthedDocumentsUploadRoute: AuthedDocumentsUploadRoute,
  AuthedDocumentsIndexRoute: AuthedDocumentsIndexRoute,
}

const AuthedDocumentsRouteWithChildren = AuthedDocumentsRoute._addFileChildren(
  AuthedDocumentsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedChatRoute: typeof AuthedChatRouteWithChildren
  AuthedDocumentsRoute: typeof AuthedDocumentsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRoute: AuthedChatRouteWithChildren,
  AuthedDocumentsRoute: AuthedDocumentsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
